config/routes.rb
Bedazzle::Application.routes.draw do

  # devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :twilios

  root to: "homes#index"
  # root to: "events#index"
  resources :events
  resources :players, :only => [:create]

  get "players" => 'players#index'
  match "twilios" => 'twilios#index'

  #for Facebook Login
  # match 'auth/facebook/callback', to: 'sessions#create'
  # match 'auth/failure', to: redirect('/')
  # match 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :end_time, :user_id, :event_status, :rating_id, :start_time, :wordnik, :party_type_id

  has_many :players, dependent: :destroy
  has_many :event_prompts, dependent: :destroy
  has_many :prompts, through: :event_prompts
  belongs_to :rating
  belongs_to :party_type
  belongs_to :user

  validates :rating_id, presence: true
  validates :party_type_id, presence: true

  validates :user_id, presence: true, uniqueness: { scope: :event_status }, if: :event_status

  before_create :add_wordnik

  def start
    # set start time to now
    self.start_time = Time.now
    self.end_time = self.start_time + 60 * 60 * 3
    self.save

    # iterate through accepted players, sending the first prompt to each - the Party Starter!
    self.players.where("accepted is true").each do |player|
      player.send_text("#{player.get_new_prompt} Respond with 'd' when done or 'p' to pass.")
    end
  end

  def end
    self.end_time = Time.now
    self.event_status = false
    self.players.where("end_time is null").each do |player|
      player.update_attributes(end_time: Time.now)
    end
    self.save
    # set end time for any open players
  end

  def add_wordnik

    # get two random words from wordnik
    word1 = get_random_word
    word2 = get_random_word

    # check to make sure they aren't the same word
    # get a new second word if they're the same
    while word1 == word2
      word2 = get_random_word
    end

    # sets the wordnik phrase for this party to a string of word1 + word2
    self.wordnik = "#{word1.downcase} #{word2.downcase}"
  end

  def get_random_word
    # gets a random Wordnik word with the following options:
    # maxLength: 7 - sets the query to pull only words 7 letters or fewer
    # includePartsOfSpeech: "noun" - calls only nouns
    # excludePartsOfSpeech: "proper-noun" - excludes proper nouns, such as "Paul"
    # excludePartsOfSpeech: "proper-noun-plural" - excludes plural proper nouns such as "Steves"
    # excludePartsOfSpeech: "proper-noun-possessive" - excludes possessive proper nouns such as "Steve's"
    # result is a hash, and we want the value of the ["word"] key
    Wordnik.words.get_random_word(maxLength: 5, includePartOfSpeech: "noun", excludePartOfSpeech: "proper-noun", excludePartOfSpeech: "proper-noun-plural", excludePartOfSpeech: "proper-noun-posessive")["word"]
  end


  # def add_user_id
  #   self.user_id = current_user.id
  # end

  def random_prompt
    # find prompts based on party type
    # where prompt.rating.value <= self.rating.value
    self.party_type.prompts.joins(:rating).where("ratings.value <= ?", self.rating.value).sample
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!
  require 'twilio-ruby'

  def index
    events = Event.where("user_id = ?", current_user.id)
    @events = events.sort_by { |k| k[:created_at] }.reverse
    @current_event = events.find_by_event_status(true)
  end

  def new
    @event = Event.new
    @party_type_id = params[:party_type_id]
  end

  def create
    @event = Event.create(params[:event])
    party_master = Player.create(name: current_user.name, phone: current_user.phone, event_id: @event.id, accepted: true)
    redirect_to event_path(@event.id)
  end

  def show
    @id = params[:id]
    @event = Event.find(@id)
    @player = Player.new
    @players = @event.players

    respond_to do |format|
      format.html
      format.json {
        render json: @players
      }
    end
  end

  def update
    @id = params[:id]

    @event = Event.find(@id)

    # if a party has never been started
    if @event.start_time == nil
      @event.start

    # if a party has already been started, stop it
    elsif @event.event_status == true
      @event.end
    end

    respond_to do |format|
      format.html {redirect_to events_path}
      format.json {render json: @event}
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper


end

app/views/events/index.html.erb
<% if current_user.present? %>
  <div class="alert alert-success text-center">Welcome <%= current_user.name %></div>
<% end %>
<% if @current_event %>
  <div class="alert alert-warning text-center">
    <p>Current party:</p>
    <h3><%= link_to "#{@current_event.wordnik}", event_path(@current_event.id) %></h3>
    <p>(end this party to create a new one)</p>
  </div>
<% else %>
  <%= button_to "Create a Party", new_event_path, method: :get, class: "btn btn-big btn-primary leder" %>
<% end %>
<table class="table">
  <thead>
    <th>Passphrase</th>
    <th>Status</th>
    <th>Players</th>
  </thead>
  <tbody>
    <% @events.each do |event| %>
    <tr>
      <td><%= link_to "#{event.wordnik}", event_path(event.id) %></td>
      <td>
        <%= "Pending" if event.start_time == nil %>
        <%= "Started" if event.event_status == true && event.start_time != nil %>
        <%= "Done" if event.event_status == false %>
      </td>
      <td><%= event.players.count %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<h3>Select party type</h3>
<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          Dinner With Friends <i class="fa fa-plus-square-o"></i>
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse">
      <div class="panel-body text-center">
        <%= form_for @event do |f| %>
          <label class="btn btn-primary rating">
            <%= f.radio_button :rating_id, '1'%>
            <span>PG</span>
          </label>
          <label class="btn btn-primary rating">
            <%= f.radio_button :rating_id, '2'%>
            <span>PG-13</span>
          </label>
          <label class="btn btn-primary rating">
            <%= f.radio_button :rating_id, '3'%>
            <span>R</span>
          </label>
          <%= f.hidden_field :party_type_id, value: 1 %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <button class='btn btn-success leder hidden fa fa-users' type="submit"> Add Users</button>
        <% end %>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          Raucous Gathering <i class="fa fa-plus-square-o"></i>
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
        <%= form_for @event do |f| %>
          <div class="rating-panel text-center">
            <label class="btn btn-primary rating">
              <%= f.radio_button :rating_id, '1'%>
              <span>PG</span>
            </label>
            <label class="btn btn-primary rating">
              <%= f.radio_button :rating_id, '2'%>
              <span>PG-13</span>
            </label>
            <label class="btn btn-primary rating">
              <%= f.radio_button :rating_id, '3'%>
              <span>R</span>
            </label>
          </div>
          <%= f.hidden_field :party_type_id, value: 2 %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <button class='btn btn-success leder hidden fa fa-users' type="submit"> Add Users</button>
        <% end %>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
          Fab Date Night <i class="fa fa-plus-square-o"></i>
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse">
      <div class="panel-body">
        <%= form_for @event do |f| %>
          <div class="rating-panel text-center">
            <label class="btn btn-primary rating">
              <%= f.radio_button :rating_id, '1'%>
              <span>PG</span>
            </label>
            <label class="btn btn-primary rating">
              <%= f.radio_button :rating_id, '2'%>
              <span>PG-13</span>
            </label>
            <label class="btn btn-primary rating">
              <%= f.radio_button :rating_id, '3'%>
              <span>R</span>
            </label>
          </div>
          <%= f.hidden_field :party_type_id, value: 3 %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <button class='btn btn-success leder hidden fa fa-users' type="submit"> Add Users</button>
        <% end %>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
          Team Building <i class="fa fa-plus-square-o"></i>
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse">
      <div class="panel-body">
        <%= form_for @event do |f| %>
          <div class="rating-panel text-center">
            <label class="btn btn-primary rating">
              <%= f.radio_button :rating_id, '1'%>
              <span>PG</span>
            </label>
            <label class="btn btn-primary rating">
              <%= f.radio_button :rating_id, '2'%>
              <span>PG-13</span>
            </label>
            <label class="btn btn-primary rating">
              <%= f.radio_button :rating_id, '3'%>
              <span>R</span>
            </label>
          </div>
          <%= f.hidden_field :party_type_id, value: 4 %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <button class='btn btn-success leder hidden fa fa-users' type="submit"> Add Users</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<% unless current_user.phone %>
  <div class="alert alert-danger">
    <p>We don't know your phone number! Be sure to add yourself as a player.</p>
  </div>
<% end %>

<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Invite Players:</h3>
  </div>
  <div class="panel-body">
    <div id="player-form">
      <form role="form">
        <div class="form-group">
          <label>Name:</label>
          <input type="text" id="name" class="form-control" name="name" value="<%= current_user.name if current_user.phone == nil && @event.players.count == 0 %>">
        </div>
        <div class="form-group">
          <label>Phone Number:</label>
          <input type="tel" class="form-control bfh-phone" data-format="(ddd) ddd-dddd" id="phone" name="phone">
        </div>
        <input type="hidden" id="event_id" value="<%= @id %>" >
        <button id="add-player" class="btn btn-info leder">Add Player</button>
      </form>
    </div>
  </div>
</div>
<div class="passphrase text-center">
  <p>or have players text</p>
  <h3><%= @event.wordnik.downcase %></h3>
  <p>- to -</p>
  <h3><%= "(#{ENV["phone"][2..4]}) #{ENV["phone"][5..7]} - #{ENV["phone"][8..11]}" %></h3>
</div>

<% unless @event.event_status == false %>
  <%= button_to "Get this party started!", "/", class: "btn btn-success btn-big #{'hidden' unless @event.start_time == nil}", id: "party-start-btn", value: "#{@id}" %>

  <%= button_to "Stop the party", event_path(@id), method: "put", class: "btn btn-danger btn-big #{'hidden' if @event.start_time == nil}", id: "party-stop-btn" %>
<% end %>

<div id="player-list">
  <h4>Invited Players</h4>
  <table class="table">
    <thead>
      <th>Name</th>
      <th>Phone #</th>
      <th>Status</th>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>